"use client";
import { FormEvent, useEffect, useState } from "react";
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000/api/v1";
type Repo = {id:string; name:string; url:string; status:string; stats:{chunks?:number; languages?:Record<string,number>}};
export default function Home() {
 const [token, setToken] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [isRegistering, setIsRegistering] = useState(false); const [repos, setRepos] = useState<Repo[]>([]); const [url,setUrl]=useState(""); const [active,setActive]=useState<Repo>(); const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState(""); const [error,setError]=useState("");
 async function authenticate(e: FormEvent) { e.preventDefault(); setError(""); const r=await fetch(`${api}/auth/${isRegistering ? "register" : "login"}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})}); if(!r.ok){setError(isRegistering ? "Could not create this account. Use a valid email and password with at least 10 characters." : "Sign in failed. Check your email and password.");return} const data=await r.json(); setToken(data.access_token); loadRepos(data.access_token); }
 async function loadRepos(t=token){const r=await fetch(`${api}/repositories`,{headers:{Authorization:`Bearer ${t}`}}); if(r.ok){const next: Repo[]=await r.json();setRepos(next);setActive(current=>current?next.find(repo=>repo.id===current.id)??current:current)}}
 useEffect(()=>{if(!token)return;loadRepos();const timer=window.setInterval(()=>loadRepos(),5000);return()=>window.clearInterval(timer)},[token]);
 async function addRepo(e:FormEvent){e.preventDefault();const r=await fetch(`${api}/repositories`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({url})});if(r.ok){setUrl("");loadRepos()}else setError(await r.text())}
 async function ask(e:FormEvent){e.preventDefault();if(!active)return;setAnswer("");const r=await fetch(`${api}/repositories/${active.id}/chat`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({question})});const reader=r.body?.getReader();if(!reader)return;const decoder=new TextDecoder();let buffer="";while(true){const x=await reader.read();if(x.done)break;buffer+=decoder.decode(x.value);const events=buffer.split("\n\n");buffer=events.pop()??"";for(const event of events){const line=event.split("\n").find(l=>l.startsWith("data: "));if(line&&event.includes("event: token"))setAnswer(a=>a+JSON.parse(line.slice(6)))}}}
 if(!token)return <main className="auth"><section><span className="eyebrow">REPOSITORY INTELLIGENCE</span><h1>Know your codebase<br/>like its author.</h1><p>Search architecture, trace behavior, and get cited technical answers from any public GitHub repository.</p></section><form onSubmit={authenticate} className="card"><h2>{isRegistering ? "Create account" : "Sign in"}</h2><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password (10+ characters)" type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/><button>{isRegistering ? "Create account" : "Continue"}</button><button className="secondary" type="button" onClick={()=>{setIsRegistering(!isRegistering);setError("")}}>{isRegistering ? "Already have an account? Sign in" : "New here? Create an account"}</button>{error&&<small>{error}</small>}</form></main>;
 return <main className="shell"><aside><div className="logo">◈ RepoSage</div><p>YOUR REPOSITORIES</p>{repos.map(r=><button className={active?.id===r.id?"repo active":"repo"} onClick={()=>setActive(r)} key={r.id}><b>{r.name}</b><span>{r.status}</span></button>)}<form onSubmit={addRepo}><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/org/repo"/><button>Add repository</button></form></aside><section className="workspace">{active?<><header><span className="eyebrow">{active.status}</span><h1>{active.name}</h1><p>{active.stats.chunks??0} indexed chunks · {Object.keys(active.stats.languages??{}).join(", ")||"indexing"}</p></header><div className="chat">{active.status!=="ready"?<div className="empty"><h2>Indexing in progress</h2><p>The repository is being cloned and analyzed. Chat will unlock automatically when indexing finishes.</p></div>:answer?<article><span className="eyebrow">AI ANALYSIS</span><p>{answer}</p></article>:<div className="empty"><h2>Ask about this repository</h2><p>Try “Where is authentication implemented?” or “Explain the architecture.”</p></div>}<form onSubmit={ask}><input disabled={active.status!=="ready"} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a technical question…"/><button disabled={active.status!=="ready"}>Send</button></form></div></>:<div className="empty"><h1>Choose a repository</h1><p>Add a public GitHub URL to begin indexing.</p></div>}</section></main>
}
